import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SolanaProvider } from "@/components/SolanaProvider";
import "./globals.css";
import Navbar from "@/components/Navigation/Navbar";


export const metadata: Metadata = {
  title: "SkillBet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <SolanaProvider><Navbar/>{children}</SolanaProvider>
      </body>
    </html>
  );
}
